### ISSUE TITLE
Installing hipFFT and RocFFT for a specific version of ROCm

### ISSUE THREAD

**Issue by bcaddy** [ROCmSoftwarePlatform/hipFFT#27]
### What is the expected behavior
-  I would like to be able to install hipFFT and RocFFT such that they reside in the same location that `hipconfig -R` returns, i.e. the ROCM_PATH

### What actually happens
-  Currently it always installs in `/opt/rocm-5.2.0`

### How to reproduce
- Install ROCm, hipFFT, and RocFFT with this script

```bash
sudo apt-get update
wget https://repo.radeon.com/amdgpu-install/22.20.1/ubuntu/focal/amdgpu-install_22.20.50201-1_all.deb
sudo apt-get install -y ./amdgpu-install_22.20.50201-1_all.deb

# Add the repo for the version of ROCm that we want
ROCM_VERSION=5.1.0
if [ "${ROCM_VERSION:0-1}" = "0" ]
then
    # If the last character is a "0" then trim the last ".0"
    ROCM_REPO_VERSION="${ROCM_VERSION:0:3}"
else
    ROCM_REPO_VERSION=$ROCM_VERSION
fi
echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/${ROCM_REPO_VERSION} ubuntu main" | sudo tee /etc/apt/sources.list.d/rocm.list
sudo apt update

# Install ROCm
sudo amdgpu-install -y --usecase=rocm --rocmrelease=${ROCM_VERSION}

# Setup hipFFT installation
sudo apt install -y gnupg2
wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian/ ubuntu main' | sudo tee /etc/apt/sources.list.d/rocm.list
sudo apt update

sudo apt install -y hipfft rocfft
```

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx90a (simulated, I'm only building, not running) |
| CPU | x86_64, it will be running on a GitHub Action eventually |

| Software | version |
ROCm 5.1.0 for now. I need a fix that I can automatically choose the version.

**Comment by bcaddy** [comment]
To add to this. If you try to install ROCm v5.2.0 with the install script and HIPFFT+RocFFT you get the following error

```
Preparing to unpack .../rocm-core_5.2.0.50200-65_amd64.deb ...
[868](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:869)
Unpacking rocm-core (5.2.0.50200-65) ...
[869](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:870)
dpkg: error processing archive /var/cache/apt/archives/rocm-core_5.2.0.50200-65_amd64.deb (--unpack):
[870](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:871)
 trying to overwrite '/opt/rocm-5.2.0/.info/version', which is also in package rocm-core5.2.0 5.2.0.50200-65
[871](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:872)
Selecting previously unselected package hipfft.
[872](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:873)
Preparing to unpack .../hipfft_1.0.8.50200-65_amd64.deb ...
[873](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:874)
Unpacking hipfft (1.0.8.50200-65) ...
[874](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:875)
Selecting previously unselected package hipfft-dev.
[875](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:876)
Preparing to unpack .../hipfft-dev_1.0.8.50200-65_amd64.deb ...
[876](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:877)
Unpacking hipfft-dev (1.0.8.50200-65) ...
[877](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:878)
Errors were encountered while processing:
[878](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:879)
 /var/cache/apt/archives/rocm-core_5.2.0.50200-65_amd64.deb
[879](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:880)
E: Sub-process /usr/bin/dpkg returned an error code (1)
[880](https://github.com/bcaddy/cholla/runs/7601446098?check_suite_focus=true#step:12:881)
Error: Process completed with exit code 100.
```

**Comment by evetsso** [comment]
Can I get some more detail on your requirements here?  Are you looking for rocFFT+hipFFT from ROCm 5.1.0 specifically, running on top of a ROCm 5.2.0 stack?

Is there a reason why rocFFT+hipFFT from ROCm 5.2.0 is not feasible?

**Comment by bcaddy** [comment]
Per my last comment, I can't get rocFFT+hipFFT and ROCm 5.2.0 to install together so using them together doesn't work.

Essentially I want to be able to install any reasonably recent version of ROCm and hipFFT+rocFFT and have them work together such that `hipconfig -R` is the root path for both. If they have to be separate I can work with that but then there should be some way to find the path to hipFFT+rocFFT with hipconfig; they also shouldn't conflict with ROCm 5.2.0.

What I ultimately want is an easy way to set the version of both so that I can run automated tests with the same version of ROCm, hipFFT, and rocFFT that we use on Frontier/Crusher.

Does that make sense?

**Comment by evetsso** [comment]
The repositories that `amdgpu-install` sets up also include rocFFT and hipFFT.  Is it sufficient if you give up on requesting a separate version of rocFFT and hipFFT and just use those?  e.g.:
```sh
sudo apt-get update
wget https://repo.radeon.com/amdgpu-install/22.20.1/ubuntu/focal/amdgpu-install_22.20.50201-1_all.deb
sudo apt-get install -y ./amdgpu-install_22.20.50201-1_all.deb

# Install ROCm
sudo amdgpu-install -y --usecase=rocm

# Setup hipFFT installation
sudo apt install -y hipfft rocfft
```
?

That way, ROCm, rocFFT, and hipFFT will all be in the same place pointed to by `hipconfig -R`.

**Comment by bcaddy** [comment]
Should that also work when installing a specific version of ROCm? Like this?

```bash
        sudo apt-get update
        wget https://repo.radeon.com/amdgpu-install/22.20.1/ubuntu/focal/amdgpu-install_22.20.50201-1_all.deb
        sudo apt-get install ./amdgpu-install_22.20.50201-1_all.deb

        echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/${ROCM_VERSION} ubuntu main" | sudo tee /etc/apt/sources.list.d/rocm.list
        sudo apt update

        # Install ROCm
        sudo amdgpu-install -y --usecase=rocm --rocmrelease=${ROCM_VERSION}

        sudo apt install -y hipfft rocfft
```

**Comment by evetsso** [comment]
Adding your own repo to sources.list.d I suspect is what's causing your problems.

I'm not deeply familiar with amdgpu-install, but I believe it only really knows how to install its matching version of ROCm.  So the one you're downloading in your examples is 5.2.1, and it will install ROCm 5.2.1.  Part of amdgpu-install's job is to add repositories for 5.2.1, which will also include matching rocFFT and hipFFT versions.  Adding additional sources for different versions is confusing things, I think.

From your comment about wanting "reasonably recent" versions of all of these things, I think just using 5.2.1 for everything would be easiest.

**Comment by bcaddy** [comment]
I agree, but I need to be able to install versions other than the latest version and what I've copied above is what the AMD docs say to do for multi-version installs which is the only place I could find info on how to install a specific version.

**Comment by evetsso** [comment]
Are you able to use different amdgpu-install packages when you need different versions of ROCm/rocFFT/hipFFT?  For example, if you need ROCm 5.1.4, can you use https://repo.radeon.com/amdgpu-install/22.10.4/ubuntu/focal/amdgpu-install_22.10.4.50104-1_all.deb instead to install ROCm + rocFFT + hipFFT?

In the general case, I don't believe a rocFFT library built against one version of ROCm is guaranteed to function correctly against another version of ROCm (even assuming you can get them both installed).  Some versions of ROCm have bumped versions of shared objects, so the exact libraries you need might not even be present in another version.

**Comment by cgmb** [comment]
> I'm not deeply familiar with amdgpu-install, but I believe it only really knows how to install its matching version of ROCm.

I thought that `amdgpu-install` would be able install packages for any previous ROCm release (including math library packages like rocfft and hipfft). That said, I don't have much experience with that sort of thing myself. I could be mistaken, but I think @Mystro256 helped to develop `amdgpu-install`, though, so perhaps he can clarify?

**Comment by bcaddy** [comment]
The documentation says that the install script can install previous versions as well if you set up the repo

https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.2.1/page/How_to_Install_ROCm.html#d25e641

**Comment by bcaddy** [comment]
@evetsso, your solution for installing the latest version of ROCm, hipFFT, and rocFFT does work and installs everything in `/opt/rocm-5.2.1`. However, I do get the following warning many times when compiling along with the attached error window

```
Traceback (most recent call last):
	File "/opt/rocm-5.2.1/bin/rocm agent _enumerator", line 257, in «module>
		main()
	File "/opt/rocm-5.2.1/bin/rocm_agent_enumerator", line 241, in main
		target list = readFromKFD()
	File "/opt/rocm-5.2.1/bin/rocm agent _enumerator", line 193, in readFromKFD
		for node in sorted(os.listdir (topology dir)) :
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/kfd/kfd/topology/nodes/
```
<img width="578" alt="Screen Shot 2022-08-06 at 15 23 56" src="https://user-images.githubusercontent.com/41171425/183273296-60e68831-2971-41f0-aa5b-0688c5002b80.png">


I think I've figured out how to install older versions of ROCm+hipFFT+rocFFT but I have a question. When I add the appropriate versions repo I get two new hipFFT/rocFFT packages, a regular version and a version with `-dev` in the name, and I'm not sure what the difference is and which I should install?

**Comment by evetsso** [comment]
As is customary in Debian-based distributions like Ubuntu, the undecorated library packages (rocfft, hipfft) are what you need at runtime (i.e. to execute programs that depend on these libraries).  The -dev packages are what you need for development (i.e. to compile and link programs that depend on these libraries).

As for documentation, that can always be improved without a doubt.  I suspect what's going on here is the amdgpu-install and package manager install methods are not really supposed to be mixed, but this is not made clear in the documentation.  I will see if that can be improved.

Since it sounds like you've got a working install, I will close this issue.  Please feel free to comment and/or reopen if you have further problems.

**Comment by bcaddy** [comment]
Thank you for your help.

> the amdgpu-install and package manager install methods are not really supposed to be mixed

Can I install hipFFT and rocFFT with the amdgpu-install method? I looked for that but couldn't find any way to do it

**Comment by evetsso** [comment]
Once you have amdgpu-install set up the repositories, you can install rocfft, rocfft-dev, hipfft, hipfft-dev using apt.  Perhaps that's where the confusion comes from, because amdgpu-install is setting up the repositories and installing some packages, but you can (and should) still use the package manager to ask for additional things.

But once amdgpu-install has set up repositories for you, you probably don't want to set up additional repositories manually, since those can conflict with what amdgpu-install has already done.

I'm not an expert in this topic, but I suspect this is what's happened.

**Comment by bcaddy** [comment]
That's definitely where the confusion is coming from. Thanks

**Comment by Mystro256** [comment]
> > I'm not deeply familiar with amdgpu-install, but I believe it only really knows how to install its matching version of ROCm.
> 
> I thought that `amdgpu-install` would be able install packages for any previous ROCm release (including math library packages like rocfft and hipfft). That said, I don't have much experience with that sort of thing myself. I could be mistaken, but I think @Mystro256 helped to develop `amdgpu-install`, though, so perhaps he can clarify?

For reference, the build system produces packages like "rocfft" and also copies called "rocfft5.2.0". The latter package is used for multi rocm installs, since package managers do not allow 2 different packages with the same name but different version to be installed. The latter "rocfft5.2.0" has the version embedded in the name, so it wouldn't conflict with say a "rocfft5.1.0" package.

amdgpu-install is just a wrapper for the package manager (apt, yum, dnf, zypper), so there's nothing stopping you from using the package manager directly to install packages instead.

Running amdgpu-install will just call the package manager to install a package, such as packageX, while adding --rocmrelease=5.2.0 would instead install the packageX5.2.0 package instead. You can run amdgpu-install with the --dry-run option to print what commands it was going to run instead of actually running them.

**Comment by bcaddy** [comment]
Thank you, this is very helpful!
